<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Fennec.Core\Fennec.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.1" />
    <PackageReference Include="SQLitePCLRaw.provider.winsqlite3" Version="3.0.5" />
  </ItemGroup>
</Project>
